version:        "0-1"
api:            "http://localhost:8888/TestamentsDePoilus/api/web/app_dev.php"
api_web:        "http://localhost:8888/TestamentsDePoilus/api/web/"
iiif:
    server: "https://testaments-de-poilus.huma-num.fr/iiif/2"
    separator: "K"
    extension: "_L"
webapp:
    strict:     "http://localhost:8888/TestamentsDePoilus/webapp/app/#!/"
    resources:  "http://localhost:8888/TestamentsDePoilus/webapp/app/web/"
siteURL:        "http://testament-de-poilus.huma-num.fr"
client_id:      "1_3bcbxd9e24g0gk4swg0kwgcwg4o8k8g4g888kwc44gcc0gwwk4"
client_secret:  "4ok2x70rlfokc8g0wws8c8kwcokw80k44sg48goc0ok4w0so0k"